# .travis.yml
sudo: false
language: php

php:
  - 7.4

env:
  - TYPO3_VERSION=^10

branches:
  only:
    - master

matrix:
  include:
    - php: 7.4
      env: TYPO3_VERSION=^10

addons:
  apt:
    packages:
      - parallel

install:
  - composer require typo3/minimal:${TYPO3_VERSION}
  - git checkout composer.json
  - export TYPO3_PATH_WEB="$PWD/.build/web"

script:
  - composer create-libs && ls -la Libraries/*.phar | grep -v ^-rwx

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    - rb@buechler.pro
